
class BibleData {
  static List<Map<String, dynamic>> get verses => [];

  static const List<Map<String, dynamic>> books = [
    {'id':1,'name':'ఆదికాండము','nameEnglish':'Genesis','testament':'OT','totalChapters':50,'orderIndex':1},
    {'id':2,'name':'నిర్గమకాండము','nameEnglish':'Exodus','testament':'OT','totalChapters':40,'orderIndex':2},
    {'id':3,'name':'లేవీయకాండము','nameEnglish':'Leviticus','testament':'OT','totalChapters':27,'orderIndex':3},
    {'id':4,'name':'సంఖ్యాకాండము','nameEnglish':'Numbers','testament':'OT','totalChapters':36,'orderIndex':4},
    {'id':5,'name':'ద్వితీయోపదేశకాండము','nameEnglish':'Deuteronomy','testament':'OT','totalChapters':34,'orderIndex':5},
    {'id':6,'name':'యెహోషువ','nameEnglish':'Joshua','testament':'OT','totalChapters':24,'orderIndex':6},
    {'id':7,'name':'న్యాయాధిపతులు','nameEnglish':'Judges','testament':'OT','totalChapters':21,'orderIndex':7},
    {'id':8,'name':'రూతు','nameEnglish':'Ruth','testament':'OT','totalChapters':4,'orderIndex':8},
    {'id':9,'name':'1 సమూయేలు','nameEnglish':'1 Samuel','testament':'OT','totalChapters':31,'orderIndex':9},
    {'id':10,'name':'2 సమూయేలు','nameEnglish':'2 Samuel','testament':'OT','totalChapters':24,'orderIndex':10},
    {'id':11,'name':'1 రాజులు','nameEnglish':'1 Kings','testament':'OT','totalChapters':22,'orderIndex':11},
    {'id':12,'name':'2 రాజులు','nameEnglish':'2 Kings','testament':'OT','totalChapters':25,'orderIndex':12},
    {'id':13,'name':'1 దినవృత్తాంతములు','nameEnglish':'1 Chronicles','testament':'OT','totalChapters':29,'orderIndex':13},
    {'id':14,'name':'2 దినవృత్తాంతములు','nameEnglish':'2 Chronicles','testament':'OT','totalChapters':36,'orderIndex':14},
    {'id':15,'name':'ఎజ్రా','nameEnglish':'Ezra','testament':'OT','totalChapters':10,'orderIndex':15},
    {'id':16,'name':'నెహెమ్యా','nameEnglish':'Nehemiah','testament':'OT','totalChapters':13,'orderIndex':16},
    {'id':17,'name':'ఎస్తేరు','nameEnglish':'Esther','testament':'OT','totalChapters':10,'orderIndex':17},
    {'id':18,'name':'యోబు','nameEnglish':'Job','testament':'OT','totalChapters':42,'orderIndex':18},
    {'id':19,'name':'కీర్తనలు','nameEnglish':'Psalms','testament':'OT','totalChapters':150,'orderIndex':19},
    {'id':20,'name':'సామెతలు','nameEnglish':'Proverbs','testament':'OT','totalChapters':31,'orderIndex':20},
    {'id':21,'name':'ప్రసంగి','nameEnglish':'Ecclesiastes','testament':'OT','totalChapters':12,'orderIndex':21},
    {'id':22,'name':'పరమగీతము','nameEnglish':'Song of Solomon','testament':'OT','totalChapters':8,'orderIndex':22},
    {'id':23,'name':'యెషయా','nameEnglish':'Isaiah','testament':'OT','totalChapters':66,'orderIndex':23},
    {'id':24,'name':'యిర్మీయా','nameEnglish':'Jeremiah','testament':'OT','totalChapters':52,'orderIndex':24},
    {'id':25,'name':'విలాపవాక్యములు','nameEnglish':'Lamentations','testament':'OT','totalChapters':5,'orderIndex':25},
    {'id':26,'name':'యెహెజ్కేలు','nameEnglish':'Ezekiel','testament':'OT','totalChapters':48,'orderIndex':26},
    {'id':27,'name':'దానియేలు','nameEnglish':'Daniel','testament':'OT','totalChapters':12,'orderIndex':27},
    {'id':28,'name':'హోషేయ','nameEnglish':'Hosea','testament':'OT','totalChapters':14,'orderIndex':28},
    {'id':29,'name':'యోవేలు','nameEnglish':'Joel','testament':'OT','totalChapters':3,'orderIndex':29},
    {'id':30,'name':'ఆమోసు','nameEnglish':'Amos','testament':'OT','totalChapters':9,'orderIndex':30},
    {'id':31,'name':'ఓబద్యా','nameEnglish':'Obadiah','testament':'OT','totalChapters':1,'orderIndex':31},
    {'id':32,'name':'యోనా','nameEnglish':'Jonah','testament':'OT','totalChapters':4,'orderIndex':32},
    {'id':33,'name':'మీకా','nameEnglish':'Micah','testament':'OT','totalChapters':7,'orderIndex':33},
    {'id':34,'name':'నహూము','nameEnglish':'Nahum','testament':'OT','totalChapters':3,'orderIndex':34},
    {'id':35,'name':'హబక్కూకు','nameEnglish':'Habakkuk','testament':'OT','totalChapters':3,'orderIndex':35},
    {'id':36,'name':'జెఫన్యా','nameEnglish':'Zephaniah','testament':'OT','totalChapters':3,'orderIndex':36},
    {'id':37,'name':'హగ్గయి','nameEnglish':'Haggai','testament':'OT','totalChapters':2,'orderIndex':37},
    {'id':38,'name':'జెకర్యా','nameEnglish':'Zechariah','testament':'OT','totalChapters':14,'orderIndex':38},
    {'id':39,'name':'మలాకీ','nameEnglish':'Malachi','testament':'OT','totalChapters':4,'orderIndex':39},
    {'id':40,'name':'మత్తయి','nameEnglish':'Matthew','testament':'NT','totalChapters':28,'orderIndex':40},
    {'id':41,'name':'మార్కు','nameEnglish':'Mark','testament':'NT','totalChapters':16,'orderIndex':41},
    {'id':42,'name':'లూకా','nameEnglish':'Luke','testament':'NT','totalChapters':24,'orderIndex':42},
    {'id':43,'name':'యోహాను','nameEnglish':'John','testament':'NT','totalChapters':21,'orderIndex':43},
    {'id':44,'name':'అపొస్తలుల కార్యములు','nameEnglish':'Acts','testament':'NT','totalChapters':28,'orderIndex':44},
    {'id':45,'name':'రోమీయులకు','nameEnglish':'Romans','testament':'NT','totalChapters':16,'orderIndex':45},
    {'id':46,'name':'1 కొరింథీయులకు','nameEnglish':'1 Corinthians','testament':'NT','totalChapters':16,'orderIndex':46},
    {'id':47,'name':'2 కొరింథీయులకు','nameEnglish':'2 Corinthians','testament':'NT','totalChapters':13,'orderIndex':47},
    {'id':48,'name':'గలతీయులకు','nameEnglish':'Galatians','testament':'NT','totalChapters':6,'orderIndex':48},
    {'id':49,'name':'ఎఫెసీయులకు','nameEnglish':'Ephesians','testament':'NT','totalChapters':6,'orderIndex':49},
    {'id':50,'name':'ఫిలిప్పీయులకు','nameEnglish':'Philippians','testament':'NT','totalChapters':4,'orderIndex':50},
    {'id':51,'name':'కొలొస్సయులకు','nameEnglish':'Colossians','testament':'NT','totalChapters':4,'orderIndex':51},
    {'id':52,'name':'1 థెస్సలొనీకయులకు','nameEnglish':'1 Thessalonians','testament':'NT','totalChapters':5,'orderIndex':52},
    {'id':53,'name':'2 థెస్సలొనీకయులకు','nameEnglish':'2 Thessalonians','testament':'NT','totalChapters':3,'orderIndex':53},
    {'id':54,'name':'1 తిమోతికి','nameEnglish':'1 Timothy','testament':'NT','totalChapters':6,'orderIndex':54},
    {'id':55,'name':'2 తిమోతికి','nameEnglish':'2 Timothy','testament':'NT','totalChapters':4,'orderIndex':55},
    {'id':56,'name':'తీతుకు','nameEnglish':'Titus','testament':'NT','totalChapters':3,'orderIndex':56},
    {'id':57,'name':'ఫిలేమోనుకు','nameEnglish':'Philemon','testament':'NT','totalChapters':1,'orderIndex':57},
    {'id':58,'name':'హెబ్రీయులకు','nameEnglish':'Hebrews','testament':'NT','totalChapters':13,'orderIndex':58},
    {'id':59,'name':'యాకోబు','nameEnglish':'James','testament':'NT','totalChapters':5,'orderIndex':59},
    {'id':60,'name':'1 పేతురు','nameEnglish':'1 Peter','testament':'NT','totalChapters':5,'orderIndex':60},
    {'id':61,'name':'2 పేతురు','nameEnglish':'2 Peter','testament':'NT','totalChapters':3,'orderIndex':61},
    {'id':62,'name':'1 యోహాను','nameEnglish':'1 John','testament':'NT','totalChapters':5,'orderIndex':62},
    {'id':63,'name':'2 యోహాను','nameEnglish':'2 John','testament':'NT','totalChapters':1,'orderIndex':63},
    {'id':64,'name':'3 యోహాను','nameEnglish':'3 John','testament':'NT','totalChapters':1,'orderIndex':64},
    {'id':65,'name':'యూదా','nameEnglish':'Jude','testament':'NT','totalChapters':1,'orderIndex':65},
    {'id':66,'name':'ప్రకటన','nameEnglish':'Revelation','testament':'NT','totalChapters':22,'orderIndex':66},
  ];
}
