class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'te': {
      'appName': 'బైబిల్ సరళీకృతం',
      'appSubtitle': 'పరిశుద్ధ గ్రంథము (సరళీకృతం)',
      'home': 'హోమ్',
      'library': 'లైబ్రరీ',
      'bookmarks': 'బుక్‌మార్క్స్',
      'highlights': 'హైలైట్స్',
      'notes': 'నోట్స్',
      'settings': 'సెట్టింగ్స్',
      'search': 'వెతకండి',
      'searchHint': 'పుస్తకం, అధ్యాయం లేదా పదం ద్వారా వెతకండి...',
      'searchResults': 'వెతికిన ఫలితాలు',
      'noResults': 'ఫలితాలు ఏవీ లభించలేదు.',
      'dailyVerse': 'ఈనాటి వాక్యం',
      'dailyVerseSubtitle': 'ఈరోజు మీ కొరకు దేవుని వాగ్దానం',
      'oldTestament': 'పాత నిబంధన',
      'newTestament': 'నూతన నిబంధన',
      'chooseBook': 'పుస్తకాన్ని ఎంచుకోండి',
      'chooseChapter': 'అధ్యాయాన్ని ఎంచుకోండి',
      'originalScripture': 'మూల వాక్యం (Original)',
      'simplifiedScripture': 'సరళీకృత వాక్యం (Simplified)',
      'bothCombined': 'రెండూ కలిపి (Both)',
      'original': 'మూల వాక్యం',
      'simple': 'సరళీకృత వాక్యం',
      'fontSize': 'అక్షరాల పరిమాణం',
      'readingMode': 'పఠన మోడ్',
      'theme': 'థీమ్ (Theme)',
      'systemTheme': 'సిస్టమ్ థీమ్',
      'lightMode': 'లైట్ మోడ్',
      'darkMode': 'డార్క్ మోడ్',
      'save': 'సేవ్ చేయి',
      'clear': 'తీసివేయి',
      'aboutApp': 'యాప్ గురించి',
      'developedBy': 'డెవలపర్',
      'developerName': 'శామ్ (Sam)',
      'appVersion': 'వెర్షన్ 1.0.0',
      'aboutText': 'ఈ పరిశుద్ధ గ్రంథ సరళీకృత అప్లికేషన్ దేవుని వాక్యాన్ని ప్రతి ఒక్కరూ సులభంగా అర్థం చేసుకునే విధంగా రూపొందించబడింది.',
      'share': 'షేర్ చేయి',
      'copy': 'కాపీ చేయి',
      'bookmark': 'బుక్‌మార్క్',
      'highlight': 'హైలైట్',
      'addNote': 'నోట్ రాయండి',
      'editNote': 'నోట్ సవరించండి',
      'delete': 'తొలగించు',
      'copied': 'క్లిప్‌బోర్డ్‌కి కాపీ చేయబడింది!',
      'bookmarkAdded': 'బుక్‌మార్క్‌లకు జోడించబడింది!',
      'bookmarkRemoved': 'బుక్‌మార్క్‌ల నుండి తీసివేయబడింది!',
      'highlightAdded': 'హైలైట్ జోడించబడింది!',
      'highlightRemoved': 'హైలైట్ తీసివేయబడింది!',
      'noteSaved': 'నోట్ సేవ్ చేయబడింది!',
      'noteDeleted': 'నోట్ తొలగించబడింది!',
      'noBookmarksYet': 'బుక్‌మార్క్స్ ఏవీ లేవు',
      'noBookmarksDesc': 'ముఖ్యమైన వాక్యాలను చదివేటప్పుడు వాటిని లాంగ్ ప్రెస్ చేసి బుక్‌మార్క్ చేసుకోండి.',
      'noHighlightsYet': 'హైలైట్స్ ఏవీ లేవు',
      'noHighlightsDesc': 'నచ్చిన వాక్యాలను వేర్వేరు రంగులలో హైలైట్ చేసుకోవచ్చు.',
      'noNotesYet': 'నోట్స్ ఏవీ లేవు',
      'noNotesDesc': 'వాక్యాన్ని సెలెక్ట్ చేసి "నోట్ రాయండి" క్లిక్ చేయడం ద్వారా నోట్స్ రాసుకోవచ్చు.',
      'enterNoteText': 'ఈ వచనం గురించి మీ ఆలోచనలను ఇక్కడ రాయండి...',
      'selectHighlightColor': 'హైలైట్ రంగును ఎంచుకోండి',
      'welcomeText': 'ప్రభువు నందు ప్రియులారా, వందనములు!',
      'quickRead': 'త్వరిత పఠనం',
      'randomVerseBtn': 'యాదృచ్ఛిక వచనం',
      'searchBtn': 'శోధన',
      'language': 'భాష (Language)',
      'selectLanguage': 'భాషను ఎంచుకోండి / Select Language',
      'telugu': 'తెలుగు (Telugu)',
      'english': 'English (ఇంగ్లీష్)',
    },
    'en': {
      'appName': 'Bible Simplified',
      'appSubtitle': 'Holy Bible (Simplified)',
      'home': 'Home',
      'library': 'Library',
      'bookmarks': 'Bookmarks',
      'highlights': 'Highlights',
      'notes': 'Notes',
      'settings': 'Settings',
      'search': 'Search',
      'searchHint': 'Search by book, chapter or word...',
      'searchResults': 'Search Results',
      'noResults': 'No results found.',
      'dailyVerse': 'Daily Verse',
      'dailyVerseSubtitle': "God's promise for you today",
      'oldTestament': 'Old Testament',
      'newTestament': 'New Testament',
      'chooseBook': 'Choose Book',
      'chooseChapter': 'Choose Chapter',
      'originalScripture': 'Original Scripture',
      'simplifiedScripture': 'Simplified Scripture',
      'bothCombined': 'Both Combined',
      'original': 'Original Scripture',
      'simple': 'Simplified Scripture',
      'fontSize': 'Font Size',
      'readingMode': 'Reading Mode',
      'theme': 'Theme',
      'systemTheme': 'System Theme',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'save': 'Save',
      'clear': 'Clear',
      'aboutApp': 'About App',
      'developedBy': 'Developer',
      'developerName': 'Sam',
      'appVersion': 'Version 1.0.0',
      'aboutText': 'This Holy Bible (Simplified) application is designed to help everyone understand God\'s word easily. It provides clear, simplified explanations for difficult passages.',
      'share': 'Share',
      'copy': 'Copy',
      'bookmark': 'Bookmark',
      'highlight': 'Highlight',
      'addNote': 'Add Note',
      'editNote': 'Edit Note',
      'delete': 'Delete',
      'copied': 'Copied to clipboard!',
      'bookmarkAdded': 'Added to bookmarks!',
      'bookmarkRemoved': 'Removed from bookmarks!',
      'highlightAdded': 'Highlight added!',
      'highlightRemoved': 'Highlight removed!',
      'noteSaved': 'Note saved!',
      'noteDeleted': 'Note deleted!',
      'noBookmarksYet': 'No bookmarks yet',
      'noBookmarksDesc': 'Long-press any verse while reading to save it to your bookmarks.',
      'noHighlightsYet': 'No highlights yet',
      'noHighlightsDesc': 'Highlight favorite verses in various beautiful colors.',
      'noNotesYet': 'No notes yet',
      'noNotesDesc': 'Select a verse and click "Add Note" to write down your reflections.',
      'enterNoteText': 'Write your thoughts about this verse here...',
      'selectHighlightColor': 'Select highlight color',
      'welcomeText': 'Welcome in the name of the Lord!',
      'quickRead': 'Quick Read',
      'randomVerseBtn': 'Random Verse',
      'searchBtn': 'Search',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'telugu': 'తెలుగు (Telugu)',
      'english': 'English',
    }
  };

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  static AppLocalizations of(String code) {
    return AppLocalizations(code);
  }
}
